### ISSUE TITLE
train failing  on server with several running gpu's

### ISSUE THREAD

**Issue by MoustHolmes** [ashleve/lightning-hydra-template#520]
I'm running on a server with 2 gpu's one of which is training something else. 
when running this command:
`python src/train.py trainer=gpu trainer.devices=[1]`
I get this error this seams to me that the gpu ran out of memory (i also tried with setting the batch_size way down)
I think that it tries to run it on [0] which is in use instead of [1]. is `trainer.devices=[1]` not the correct argument?
`RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)
`

```
(base) [moust@hep04 work]$ gpustat
hep04.cluster               Thu Feb  9 19:29:16 2023  510.39.01
[0] NVIDIA GeForce RTX 3090 | 58°C,  84 % | 13823 / 24576 MB | qgf305(13489M) root(9M) gdm(12M)
[1] NVIDIA GeForce RTX 3090 | 35°C,   0 % |   317 / 24576 MB | root(5M)
```

full traceback
```
Traceback (most recent call last):
  File "/lustre/hpc/icecube/moust/work/GraphNet-lightning-hydra/src/utils/utils.py", line 38, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
  File "/lustre/hpc/icecube/moust/work/GraphNet-lightning-hydra/src/train.py", line 82, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 582, in fit
    call._call_and_handle_interrupt(
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run
    results = self._run_stage()
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage
    self._run_train()
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1163, in _run_train
    self.fit_loop.run()
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 214, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 200, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 247, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 357, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1305, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1661, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 234, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 121, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/torch/optim/optimizer.py", line 140, in wrapper
    out = func(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/torch/optim/optimizer.py", line 23, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/torch/optim/adam.py", line 183, in step
    loss = closure()
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 107, in _wrap_closure
    closure_result = closure()
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 147, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 142, in closure
    self._backward_fn(step_output.closure_loss)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 303, in backward_fn
    self.trainer._call_strategy_hook("backward", loss, optimizer, opt_idx)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1443, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 207, in backward
    self.precision_plugin.backward(closure_loss, self.lightning_module, optimizer, optimizer_idx, *args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 69, in backward
    model.backward(tensor, optimizer, optimizer_idx, *args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/pytorch_lightning/core/module.py", line 1406, in backward
    loss.backward(*args, **kwargs)
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/groups/icecube/moust/miniconda3/envs/hydra/lib/python3.9/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by ashleve** [comment]
It seems like it is indeed correct argument.
https://pytorch-lightning.readthedocs.io/en/stable/accelerators/gpu_basic.html?highlight=devices#choosing-gpu-devices

Have you made sure this is parsed correctly when launching through terminal? For example, some shells need to use the escape characters:
`python src/train.py trainer=gpu trainer.devices=\[1\]`

Have you made sure it's not caused by incorrect model implementation? The error message suggests the error happens during backward pass. For example, here someone suggests a similar error can be caused by tensor shape mismatch:
https://stackoverflow.com/questions/66600362/runtimeerror-cuda-error-cublas-status-execution-failed-when-calling-cublassge

**Comment by MoustHolmes** [comment]
Turns out that it wasn't a problem with the other gpu being occupied but rather a problem with with pytorch not being able to find the gpus (I think) I solved it by changing the installed torch from  `torch>=1.10.0` to `torch==1.11+cu115` and adding `torch-cluster==1.6.0` though not sure if the last one necessary.
